sources := "."

compile platform="jvm":
	scala-cli compile --test --platform {{platform}} {{sources}}

test platform="jvm":
	scala-cli test --platform {{platform}} {{sources}}

test-all: (test "jvm") (test "js") (test "native")

update:
	scala-cli dependency-update --all {{sources}}

clean:
	scala-cli clean {{sources}}
	scala-cli setup-ide {{sources}}

scalafmt:
	scala-cli fmt {{sources}}

scalafix:
	scala-cli fix --scalafix --enable-built-in=false {{sources}}

#---------8<-----------
# non shared part below

run *args:
	scala-cli run {{sources}} -- {{args}}

weekly-plots:
	scala-cli run --main-class whataretheydoing.makeWeeklyPlotSvgs {{sources}}

commit-type:
	scala-cli run --main-class whataretheydoing.makeRq2CommitTypeSvgs {{sources}}

commit-type-per-agent:
	scala-cli run --main-class whataretheydoing.makeRq2CommitTypePerAgentSvgs {{sources}}

all-rq2:
	scala-cli run --main-class whataretheydoing.makeAllRq2Svgs {{sources}}
